Copyright 2012 Mark Wolf

This file is part of OrgWolf.

OrgWolf is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

--

This file holds some bizarre test cases for org-mode files.

* Project 1
  SCHEDULED: <2012-09-28 Fri +1d>
- listitem1
- listitem2
** NEXT TODO [#A] Heading 3
   SCHEDULED: <2012-10-10 Wed> DEADLINE: <2012-09-30 Sun>
** DONE Heading 4						       :home:
   CLOSED: [2012-09-28 Fri 08:55]
* [2012-10-13 Sat]
* 
*** aMAZING: NOTATAG:
* Project 3
