# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 21:04
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgwolf', '0001_upgrade_to_django_1_9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgwolfuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
