# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-21 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gtd', '0001_upgrade_to_django_1_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='todostate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priority',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noderepetition',
            name='new_todo_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repetitions_new_set', to='gtd.TodoState'),
        ),
        migrations.AddField(
            model_name='noderepetition',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtd.Node'),
        ),
        migrations.AddField(
            model_name='noderepetition',
            name='original_todo_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repetitions_original_set', to='gtd.TodoState'),
        ),
        migrations.AddField(
            model_name='node',
            name='focus_areas',
            field=models.ManyToManyField(blank=True, to='gtd.FocusArea'),
        ),
        migrations.AddField(
            model_name='node',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_node_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='gtd.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='todo_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtd.TodoState'),
        ),
        migrations.AddField(
            model_name='node',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='focusarea',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='context',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_node_set', to='gtd.Contact'),
        ),
        migrations.AddField(
            model_name='location',
            name='tools_available',
            field=models.ManyToManyField(blank=True, related_name='including_locations_set', to='gtd.Tool'),
        ),
        migrations.AddField(
            model_name='context',
            name='locations_available',
            field=models.ManyToManyField(blank=True, related_name='including_contexts_set', to='gtd.Location'),
        ),
        migrations.AddField(
            model_name='context',
            name='people_required',
            field=models.ManyToManyField(blank=True, related_name='including_contexts_set', to='gtd.Contact'),
        ),
        migrations.AddField(
            model_name='context',
            name='tools_available',
            field=models.ManyToManyField(blank=True, related_name='including_contexts_set', to='gtd.Tool'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
