# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0003_upgrade_to_django_1_11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderepetition',
            name='new_todo_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repetitions_new_set', to='gtd.TodoState'),
        ),
        migrations.AlterField(
            model_name='noderepetition',
            name='original_todo_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repetitions_original_set', to='gtd.TodoState'),
        ),
    ]
