# Generated by Django 2.2.10 on 2020-06-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0004_fixed_django_2_0_deprecation'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
