# Generated by Django 2.2.10 on 2021-10-14 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gtd', '0005_context_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.DateTimeField(auto_now_add=True)),
                ('finalized', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('extra_tasks', models.ManyToManyField(blank=True, related_name='weekly_review_set_as_extra', to='gtd.Node')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('primary_tasks', models.ManyToManyField(blank=True, related_name='weekly_review_set_as_primary', to='gtd.Node')),
                ('secondary_tasks', models.ManyToManyField(blank=True, related_name='weekly_review_set_as_secondary', to='gtd.Node')),
                ('tertiary_tasks', models.ManyToManyField(blank=True, related_name='weekly_review_set_as_tertiary', to='gtd.Node')),
            ],
        ),
    ]
