# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-21 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gtd', '0002_upgrade_to_django_1_9'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('sender', models.TextField(blank=True)),
                ('recipient', models.TextField(blank=True)),
                ('unread', models.BooleanField(default=True)),
                ('handler_path', models.CharField(blank=True, max_length=100)),
                ('in_inbox', models.BooleanField(default=True)),
                ('rcvd_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_text', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deferred_message', to='gtd.Node')),
                ('spawned_nodes', models.ManyToManyField(blank=True, to='gtd.Node')),
            ],
        ),
    ]
